#!/bin/sh
#
# Hellow
#


case "$1" in
  start)
	printf "Starting hellow: "
    /opt/hellow 10
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping hellow: "
    /opt/hellow
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

